# Generated by Django 5.0.4 on 2024-05-03 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth_App', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='auth_user',
        ),
    ]
